<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Ariadna Desirée Galindo Marín & Karla Antón.

**Fecha:** 09 de septiembre del 2020.

**Expediente** : 718272, 714572.
**Profesor:** Oscar David Jaramillo Zuluaga.

# Tarea 2 b: Clase 4

### Tarea:

https://github.com/ariadnagalindom/Tarea2_ADGalindo_KAnton


### Ejercicio 1:
Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:

|Order number|Book Title and Author|Quantity|Price per Item|
|-|-|-|-|
|34587|Learning Python,Mark Lutz| 4| 40.95| 
|98762|Programming Python,Mark Lutz|5|56.80| 
|77226|Head First Python,Paul Barry|3|32.95|
|88112|Einführung in Python3, Bernd Klein| 3|24.99|
           
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`

In [1]:
#solución Ariadna
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
sol1=list(map(lambda x:(x[0],x[2]*x[3])if x[2]*x[3]>=100 else (x[0],x[2]*x[3]+10),orders))
sol1

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

### Respuesta:

Para las primeras dos ordenes no superan la condición y por lo tanto no es necesario añadir +10, pero para las otras si es necesario. 

In [2]:
#solución Karla
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

S1 = list(map(lambda x:(x[0],x[2] * x[3])if x[2]*x[3] >= 100 else(x[0], x[2] * x[3] + 10), orders))
S1

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

### Respuesta:

### Ejercicio 2:
La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.


In [3]:
#solución Ariadna
from functools import reduce

orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
           [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
           [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]]

sol2 = list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2], x[1:])), orders))
sol2 = list(map(lambda x: [x[0]] + [reduce(lambda a,b: a + b, x[1:])], sol2))
sol2 = list(map(lambda x: x if (x[1] >= 100) else (x[0], x[1] + 10), sol2))

print(sol2)

[[1, 678.3299999999999], [2, 494.46000000000004], [3, 364.79999999999995], [4, 492.57]]


### Respuesta:

In [1]:
#solución Karla
from functools import reduce
orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
           [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
           [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]]
S2 = list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2], x[1:])), orders))
S2 = list(map(lambda x: [x[0]] + [reduce(lambda a,b: a + b, x[1:])], S2))
S2 = list(map(lambda x: x if (x[1] >= 100) else (x[0], x[1] + 10), S2))
print(S2)

[[1, 678.3299999999999], [2, 494.46000000000004], [3, 364.79999999999995], [4, 492.57]]


### Respuesta:

### Ejercicio 3:

Resolver lo ejercicios anteriores utilizando pandas (DataFrame)

In [3]:
#Solución Ariadna
import pandas as pd
#ejericio 1
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
ej1=pd.DataFrame(columns=["Order number","Book Title and Author","Quantity","Price per Item"], data=orders)
sol3_1=[(ej1.iloc[:,-2]*ej1.iloc[:,-1]).apply(lambda x: x if x>=100 else (x+10))]
#sol3_1=sol3_1.append(ej1.iloc[:,0])
sol3_1=pd.DataFrame(sol3_1)
sol3_1=sol3_1.append(ej1.iloc[:,0])
print(sol3_1.T)

#ejercicio 2
orders2 = [[1, "5464", 4, 9.99, "8274",18,12.99, "9744", 9, 44.95], 
           [2, "5464", 9, 9.99, "9744", 9, 44.95, 0,0,0],
           [3, "5464", 9, 9.99, "88112", 11, 24.99, 0,0,0],
           [4, "8732", 7, 11.99, "7733",11,18.99, "88112", 5, 39.95]]
ej2=pd.DataFrame(orders2)

sol3_2= [((ej2.iloc[:,2]*ej2.iloc[:,3])+(ej2.iloc[:,5]*ej2.iloc[:,6])+(ej2.iloc[:,8]*ej2.iloc[:,9])).apply(lambda x: x if x>=100 else (x+10))]
print(sol3_2)

        0 Order number
0   163.8        34587
1     284        98762
2  108.85        77226
3   84.97        88112
[0    678.33
1    494.46
2    364.80
3    492.57
dtype: float64]


In [21]:
### Solución Karla
#ejericio 1
import pandas as pd
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
S3_1 = list(map(lambda t:[t[0],t[2]*t[3] if (t[2]*t[3] > 100) else t[2]*t[3]+10], orders))
S3_1 = pd.DataFrame(S3_1)
S3_1.columns = ['Order Number', 'Total Cost']
S3_1

Order Number  Total Cost
0        34587      163.80
1        98762      284.00
2        77226      108.85
3        88112       84.97

In [22]:
#ejercicio 2
orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]

mult=lambda t:t[1]*t[2] if (t[1]*t[2] > 100) else t[1]*t[2]+10
suma = lambda a,b: a + b
S3_2= list(map(lambda x:[x[0],reduce(suma,(list(map(mult,x[1:]))))],orders))
S3_2 = pd.DataFrame(S3_2)
S3_2.columns = ['Order Number', 'Total Cost']
S3_2

Order Number  Total Cost
0             1      688.33
1             2      504.46
2             3      374.80
3             4      502.57

### Ejercicio 4. 
Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`


In [9]:
#solución Ariadna
lista='the notion of a lambda function goes all the way back to the origin of computer science'
lista=lista.split()
sol3=list(filter(lambda word: len(word)>=4, lista))
sol3
#list.split() separa la lista en palabras
#str(len(word))cuenta las letras de cada palabra

['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

### Respuesta:

In [7]:
#solución Karla
lista = "the notion of a lambda function goes all the way back to the origin of computer science"
lista = lista.split()
res= list(filter(lambda x: len(x) >= 4,lista))
res

['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

### Respuesta:

### Ejercicio 5. 
Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80


In [41]:
#solución Ariadna
import numpy as np
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
print(temperatures)
sol4=list(filter(lambda x: (x>=32 and x<=80),temper))

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


### Respuesta:

In [25]:
#solución Karla
import numpy as np
np.random.seed(55555)
temp = np.random.uniform(25,110,30)
print(temp)
S4=list(filter(lambda x: (x>=32 and x<=80),temp))

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


### Respuesta:

### Ejercicio 6. 
Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

In [4]:
#solución Ariadna
import numpy as np
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)

sol6=np.minimum.reduce(point_xy)

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [3]:
print(sol6)

[0 2]


In [9]:
#solución Karla
np.random.seed(55555)
p_xy=np.random.randint(0,100,[30,2])
print(p_xy)

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


In [11]:
np.minimum.reduce(p_xy)

array([0, 2])

### Respuesta:

## Conclusiones 

### Ariadna:

Para esta tarea tuve que recordar y juntar cosas que he visto en todos los semestres anteriores, pero con la gran diferencia de que el código esta quedando bastante resumido. Me costó mucho trabajo realizar los ejercicios, pero espero que con la práctica logre entender más sobre estas funciones para optimizar el código, pero la que más me interesa entender y practicar por el momento es *lambda* porque nos ayuda a generar funciones como parte de un argumento. 

### Karla:

En esta tarea pudimos observar que por medio de las funciones que tenemos disponibles logramos hacer nuestros códigos mucho más eficientes y fáciles de trabajar con ellos. Trabajar con estas funciones vistas en clase, nos permite la correcta manipulación ya sea de datos numéricos, cadenas de texto u otro tipo de fuentes de información. Es por ello que entender como funcionan es de gran importancia a la hora de generar nuestros códigos.